bundle:
  groupId: "org.librecores.librecores-ci"
  artifactId: "librecores-ci"
  vendor: "FOSSi"
  title: "Librecores CI"
  description: "LibreCores CI instance"
buildSettings:
  docker:
    base: "jenkins/jenkins:2.164.3"
    tag: "librecores/librecores-ci-dev"
    build: false
buildSettings:
  pom: "pom.xml"
  pomIgnoreRoot: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.164.3"
systemProperties:
  jenkins.model.Jenkins.slaveAgentPort: "50000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
  hudson.model.LoadStatistics.clock: "1000"
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: "init_scripts/src/main/groovy"
casc:
  - id: "jcasc-config"
    source:
      dir: jenkins.yaml
